nelsons/urls.py
from django.conf.urls import url

from .views import NelsonListView, NelsonCreateView, NelsonDetailView, check_existence

urlpatterns = [
    url(r'^$', NelsonListView.as_view(), name='list'),
    url(r'^create/?(?P<name>[-\w\d]*)/$', NelsonCreateView.as_view(), name='create'),
    url(r'^check/$', check_existence, name='check'),
    url(r'^(?P<pk>[-\w\d]+)$', NelsonDetailView.as_view(), name='api'),
    url(r'^(?P<pk>[-\w\d]+)/$', NelsonDetailView.as_view(), name='api'),
]

tom/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

from . import views
from hits import views as hits_views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^nelsons/', include('nelsons.urls', namespace='nelsons')),
    url(r'^admin/', admin.site.urls),
    url(r'^hits', hits_views.index),
]

hits/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.translation import ugettext as _

class Hit(models.Model):
	created_date = models.DateTimeField(_(u"Hit date"), auto_now_add=True)

nelsons/models.py
from __future__ import unicode_literals

from django.db import models

from django.utils.translation import ugettext as _
from django.utils import timezone
from datetime import timedelta

class Nelson(models.Model):
	name = models.SlugField(_(u"Name"), help_text=_(u"Enter a valid Nelson name consisting of letters, numbers, underscores or hyphens."), primary_key=True, max_length=24)

	latitude = models.DecimalField(_(u"Latitude"), max_digits = 10, decimal_places = 6, help_text=_(u"Enter a valid latitude like 48.120094"), null = True, blank = True, default = 48.120094)
	longitude = models.DecimalField(_(u"Longitude"), max_digits = 10, decimal_places = 6, help_text=_(u"Enter a valid longitude like -1.629206"), null = True, blank = True, default = -1.629206)

	position = models.PositiveSmallIntegerField(_(u"Servo position"), help_text=_(u"Enter a valid servo motor position 0 to 180"), null = False, blank = False, default = 0)

	created_date = models.DateTimeField(_(u"Created date"), auto_now_add=True)
	last_activity = models.DateTimeField(_(u"Last activity"), auto_now = True)

	def __unicode__(self):
		return self.name

	def clean(self):
		self.name = self.name.lower()

	def save(self, *args, **kwargs):
		if self.position <= 0:
			self.position = 0
		if self.position >= 180:
			self.position = 180
		super(Nelson, self).save(*args, **kwargs)

	def belongs_to(self, user):
		return user == self.edx_user

	def was_active_recently(self):
		return self.last_activity >= timezone.now() - timedelta(minutes=10)

	was_active_recently.admin_order_field = 'last_activity'
	was_active_recently.boolean = True
	was_active_recently.short_description = _(u"Active recently ?")

hits/views.py
from django.http import HttpResponse
from .models import Hit

def index(request):
    hit = Hit()
    hit.save()
    hits = Hit.objects.count()
    return HttpResponse(hits, content_type="text/plain")

nelsons/views.py
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import ListView, CreateView

from rest_framework.generics import RetrieveUpdateDestroyAPIView
from rest_framework.renderers import BrowsableAPIRenderer
from rest_framework_jsonp.renderers import JSONPRenderer

from .models import Nelson
from .serializers import NelsonSerializer


class NelsonListView(ListView):
    model = Nelson
    queryset = Nelson.objects.filter()
    context_object_name = 'nelson_list'
    template_name = 'nelsons/list.html'


class NelsonCreateView(CreateView):
    model = Nelson
    fields = ['name', 'latitude', 'longitude', 'position']
    template_name = 'nelsons/create.html'

    def get_success_url(self):
        return reverse_lazy('nelsons:api', kwargs={'pk': self.object.name})

    def get_initial(self):
        return {'name': self.kwargs['name']}


class NelsonDetailView(RetrieveUpdateDestroyAPIView):
    queryset = Nelson.objects.all()
    serializer_class = NelsonSerializer

    renderer_classes = (BrowsableAPIRenderer, JSONPRenderer,)

    def get(self, request, *args, **kwargs):
        get_position = self.request.GET.get('position')
        if get_position:
            nelson = get_object_or_404(Nelson, pk=self.kwargs.get('pk'))
            nelson.position = int(get_position)
            nelson.save()
        return self.retrieve(request, *args, **kwargs)

    def perform_update(self, serializer):
        get_position = self.request.GET.get('position')
        if get_position:
            serializer.save(position=int(get_position))
        else:
            serializer.save()


def check_existence(request):
    name = request.POST.get('name')
    try:
        nelson = Nelson.objects.get(name=name)
        return redirect(reverse_lazy('nelsons:api', kwargs={'pk': nelson.name}))
    except:
        return redirect(reverse_lazy('nelsons:create', kwargs={'name': name}))

tom/views.py
from django.http import HttpResponse

def home(request):
    return HttpResponse("Il n'y a rien ici ! Par contre, allez jeter un coup d'oeil sur la section Nelson et Tom du MOOC :)", content_type="text/plain")

nelsons/templates/nelsons/create.html
{% extends "base.html" %}
{% load i18n %}

{% block extrastyle %}
<link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.css" />
<link rel="stylesheet" type="text/css" href="http://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/0.4.0/MarkerCluster.css" />
<link rel="stylesheet" type="text/css" href="http://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/0.4.0/MarkerCluster.Default.css" />
{% endblock %}
{% block extrahead %}
<script src="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js"></script>
<script type='text/javascript' src='http://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/0.4.0/leaflet.markercluster.js'></script>
{% endblock %}

{% block title %}{% trans "Créer un Nelson" %}{% endblock %}

{% block content %}
<div class="container">
   {% if error_message %}
   <div class="alert alert-danger" role="alert">
      <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
      <span class="sr-only">Error:</span> {{ error_message }}
      </div>
   {% endif %}

   <h1>{% trans "Quelles sont les détails du Nelson à créer ?" %}</h1>

   <form class="form-horizontal" action="" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-info btn-lg">{% block submit_label %}<span class="glyphicon glyphicon-plus-sign"></span> {% trans "Create" %}{% endblock %}</button>
   </form>

   <div id="mapid" style="width:100%;height: 800px;"></div>

</div>
{% endblock %}

{% block extrascript %}
<script type="text/javascript">
   var lat_field = document.getElementById('id_latitude');
   var lon_field = document.getElementById('id_longitude');

   var map = L.map('mapid').setView([46.3630104,2.9846608], 6); //

   L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
       attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
   }).addTo(map);
   var marker = L.marker([0, 0], {draggable:'true'}).addTo(map);

   marker.on('dragend', function(event){
      var marker = event.target;
      var position = marker.getLatLng();
      lat_field.value = position.lat.toFixed(6);
      lon_field.value = position.lng.toFixed(6);
   });

   map.on('click', function(event) {
      var position = event.latlng;
      lat_field.value = position.lat.toFixed(6);
      lon_field.value = position.lng.toFixed(6);
      marker.setLatLng(position);
    });

   lat_field.addEventListener("input", updateMarker, false);
   lon_field.addEventListener("input", updateMarker, false);
   updateMarker();

   function updateMarker() {
      var lat = parseFloat(lat_field.value.replace(',', '.'));
      var lon = parseFloat(lon_field.value.replace(',', '.'));
      marker.setLatLng([lat, lon]);
      map.setView([lat, lon]);
   }


</script>
{% endblock %}

nelsons/templates/nelsons/list.html
{% extends "base.html" %}
{% load i18n %}

{% block extrastyle %}
<link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.css" />
<link rel="stylesheet" type="text/css" href="http://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/0.4.0/MarkerCluster.css" />
<link rel="stylesheet" type="text/css" href="http://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/0.4.0/MarkerCluster.Default.css" />
{% endblock %}
{% block extrahead %}
<script src="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js"></script>
<script type='text/javascript' src='http://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/0.4.0/leaflet.markercluster.js'></script>
{% endblock %}

{% block title %}{% trans "Carte des Nelsons" %}{% endblock %}

{% block content %}
<div class="container">
   <form class="form-horizontal" action="{% url 'nelsons:check' %}" method="post">
      {% csrf_token %}
      <input type="text" name="name" placeholder="Nelson à utiliser ou créer">
      <button type="submit" class="btn btn-primary btn-lg">{% block submit_label %}<span class="glyphicon glyphicon-plus-sign"></span> {% trans "Créer" %}{% endblock %}</button>
   </form>

    <hr>

    <h1>{{ nelson_list.count }} {% trans "Nelsons sont déjà enregistrés, pourquoi pas le vôtre !?" %}</h1>

    <div id="mapid" style="width:100%;height: 800px;"></div>
</div>
{% endblock %}


{% block extrascript %}
<script type="text/javascript">
    var map = L.map('mapid').setView([46.3630104,2.9846608], 6);
    var markerClusters = L.markerClusterGroup();

    L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
        attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors and <a href="https://www.fun-mooc.fr/courses/MinesTelecom/04018/session01/about">#MoocFab</a> students'
    }).addTo(map);

    {% for nelson in nelson_list %}
        var m = L.marker([{{ nelson.latitude|safe }}, {{ nelson.longitude|safe }}]).bindPopup('{{ nelson.name|slice:":3" }}' + "****");

        markerClusters.addLayer(m);
    {% endfor %}
    map.addLayer(markerClusters);
</script>
{% endblock %}

tom/templates/base.html
{% load i18n static %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE|default:"fr" }}">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{% trans "TOM : how TO build a connected thing Mooc" %}">
    <meta name="author" content="{{ author|default:"Baptiste Gaultier" }}">

    <title>{% block title %}{% endblock %} · Tom</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Font awesome CSS -->
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    {% block extrastyle %}{% endblock %}
    {% block extrahead %}{% endblock %}

    <!-- Custom style -->
    <link href="{% static 'css/tom.css' %}" rel="stylesheet">

  </head>
  <body>
      {% block content %}
      {% endblock %}

      <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
      <script src="{% static 'js/jquery.min.js' %}"></script>
      <!-- Include all compiled plugins (below), or include individual files as needed -->
      <script src="{% static 'js/bootstrap.min.js' %}"></script>
      {% block extrascript %}
      {% endblock %}
  </body>
</html>